apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
      app: streamlit-app
  type: NodePort
  selector:
    app: streamlit-app
  ports:
    - port: 8080
      nodePort: 30001